### ISSUE TITLE
can you export ActivityId and relatedActivityID?

### ISSUE THREAD

**Issue by wesley2005** [0xrawsec/golang-etw#1]
ActivityId is in e.EventRec.EventHeader.ActivityId.
relatedActivityID is in e.EventRec.ExtendedData.DataPtr when e.EventRec.ExtendedData.ExtType equal EVENT_HEADER_EXT_TYPE_RELATED_ACTIVITYID (0x0001)

**Comment by qjerome** [comment]
Do you have an example of provider+event ID that I could use to test that out ?

**Comment by wesley2005** [comment]
> Do you have an example of provider+event ID that I could use to test that out ?

{8C416C79-D49B-4F01-A467-E56D3AA8234C} Microsoft-Windows-Win32k
It has ActivityId . I don't find relatedActivityID example now.
Thanks!

**Comment by qjerome** [comment]
Thank you for your input, I'll first integrate ActivityId as it is pretty straightforward.
RelatedActivityId might be a little more work as I did not dive yet into parsing ExtendedData.
Just to satisfy my own curiosity and also because ETW is pretty mysterious sometimes, what will be your use case of those two fields ?

**Comment by wesley2005** [comment]
> Thank you for your input, I'll first integrate ActivityId as it is pretty straightforward. RelatedActivityId might be a little more work as I did not dive yet into parsing ExtendedData. Just to satisfy my own curiosity and also because ETW is pretty mysterious sometimes, what will be your use case of those two fields ?

{A103CABD-8242-4A93-8DF5-1CDF3B3F26A6} Microsoft-Windows-Kernel-IoTrace
It has ActivityId  and relatedActivityID !
Thanks!

**Comment by wesley2005** [comment]
I use ActivityId and relatedActivityID in my defined provider. It is convenient for me to trace the performance of my software.^_^

**Comment by wesley2005** [comment]
https://github.com/microsoft/ETW2JSON/blob/master/Deserializer/RuntimeEventMetadata.cs
It has query RelatedActivityId example.

**Comment by qjerome** [comment]
Hey @wesley2005,
It should be working, please let me know if it works with your use case.

**Comment by wesley2005** [comment]
> Hey @wesley2005, It should be working, please let me know if it works with your use case.

It works well in my case.
Thank you very much, my friend!

**Comment by qjerome** [comment]
great ! thanks for your feedback
