### ISSUE TITLE
how to trace the provider "Microsoft-Windows-Security-Auditing"

### ISSUE THREAD

**Issue by aboutbo** [0xrawsec/golang-etw#3]
I use golang-etw to trace "Microsoft-Windows-Security-Auditing", but I can't get any event.

**Comment by qjerome** [comment]
You cannot because it's a protected channel, only some protected processes can access it. The only way to get "Microsoft-Windows-Security-Auditing" events by enabling events via audipol command or similar and listening to the Security channel.
-------- Message d'origine --------

**Comment by aboutbo** [comment]
I trace the session "EventLog-Security" in "system" prividge, then I get the logs
